// Generated by CoffeeScript 1.10.0
(function() {
  if (Meteor.isClient) {
    Template.registerHelper('momentumIRTransition', function() {
      return function(from, to, element) {
        return "fade";
      };
    });
  }

}).call(this);
